### ISSUE TITLE
程式碼顯示問題

### ISSUE THREAD

**Issue by tigercosmos** [TechBridgeWeekly/blog-starter-kit#18]
感覺不像 CSS 沒有載入，換瀏覽器也沒用，刷新好多次還是一樣

圖片：
<img width="838" alt="2018-05-13 12 04 48" src="https://user-images.githubusercontent.com/18013815/39959225-5357c054-5641-11e8-9584-73dacbf3c881.png">

**Comment by tigercosmos** [comment]
我覺得跟這次更新有關

https://github.com/TechBridgeWeekly/techbridgeweekly.github.io/commit/d0fe3aadafbfeca6759293d255d68997ee3c5c0b

cc @kdchang

**Comment by aszx87410** [comment]
之前我也有碰過這種狀況，我自己的解決方法是把空行加上兩個空格，就會正常顯示了
像這樣：https://github.com/TechBridgeWeekly/blog-starter-kit/commit/04d8bd1e45abe11dd31cee96bc4eab48b1c5eaae#diff-b7cff3347459137ae5b9633cf8c939baR153
仔細看就會發現我有加兩個空格

@ArvinH 之前也有碰過這問題，但我忘記他怎麼解的了
