### ISSUE TITLE
mathjax 的 configuration 設定

### ISSUE THREAD

**Issue by renewang** [TechBridgeWeekly/blog-starter-kit#6]
TechBridge 的 編輯們，你們好：

我嘗試要將我的 jupyter notebook (python kernel) 轉成 mark down ，再用 hexo 重新編譯，卻在 compile 的時候遇到問題（主要是 template render error）。我不大熟悉如何  debug  node.js app，也對前端不是很熟悉。再用土法煉鋼的方法窄化可能的問題後，發現是方程式裡的 latex 符號 MathJax 無法顯示。我照著 hexo-math 的說明，稍微試了一下 mathjax 的 configuration，目前是可以顯示簡單的數學式。（就像 hexo-math 給的例子）但我的數學式還是不能過 hexo 的編譯。

在  [latex online editor](https://www.codecogs.com/latex/eqneditor.php) 顯示出來是這樣的：
![image](https://user-images.githubusercontent.com/4778331/30463741-1da37686-9a00-11e7-9543-c373a320ad4c.png)

我本身是用 python ，不是很熟悉 node.js / hexo ，以及為了要顯示 math 可能要更動貴網站 _config.yml 檔案增加 mathjax 的設定。所以不知道有沒有前端的高手，可以提供經驗，該如何設定才能顯示方程式。感恩～

Rene

**Comment by kdchang** [comment]
@renewang  您好

請教您 git clone 下來是否有先 npm install 呢？或許可以參考看看這個包在 endraw 裡面？
https://hexo.io/zh-tw/docs/troubleshooting.html#脫逸（Escape）內容

```
{% raw %}
Hello {{ sensitive }}
{% endraw %}
```

另外您可以在 local side 先加入並使用 $ hexo g && hexo s 在 localhost 看一下效果是否如您預期，若有的話可以加入 config 發 PR 過來

最後真的沒辦法的話可能要請您使用方程式圖片截圖的方式了，謝謝您，期待您的作品，加油～

**Comment by kdchang** [comment]
@renewang 請問後來處理還順利嗎？

**Comment by renewang** [comment]
最近沒有什麼時間在弄這件事，今天晚上又稍微查 google 了一下 hexo-math，應該是我用 nbconvert 將  python jupyter notebook 轉成 python markdown，在跳脫符號上面有一些編譯問題，導致 hexo 不能正確編譯。正確跳脫 tex 方程式後，編譯就過了（主要是看這篇啦：http://kubicode.me/2016/03/18/Hexo/The-Trick-about-Hexo-Support-MutliLine-Equation-using-Mathjax/ <http://kubicode.me/2016/03/18/Hexo/The-Trick-about-Hexo-Support-MutliLine-Equation-using-Mathjax/>，不過也不是很懂這位作者在說什麼就是了，和他找到 solution  的方式。）。另外，我加了 mathjax 的 configuration 到 _config.yml  裡，主要是加 cdnjs 的部分。（好像光 install hexo-math 我 local 端數學式還是出不來。）目前，還有一些排版的問題，以及我需要將原本在 notebook 動態的部分，export 靜態的圖。就可以發 PR 給各位 review 了。

另外我想問一下，各位有使用 jupyter notebook 的經驗嗎？我在想，我大多的時候都是用 python3 kernel，不知道各位是否能給一些建議，如何有效地避免上面跳脫符號的問題？因為要手動更改數學式（像換行之類的）應該對我還滿常見的。
謝謝！

**Comment by kdchang** [comment]
辛苦了，我平常也會寫 data analytics/data science 相關應用，也會用到 jupyter notebook 。但 hexo 上放 jupyter notebook 我目前還沒試過，可能要再找一下資料，謝謝～

**Comment by renewang** [comment]
我目前有的想法可能是用 nbconvert 做。有可能的做法，可能是寫一個  python application 作為 nbconvert api 的 wrapper， 在 application 裡寫一個 preprocessor  將 markdown cell 裡的數學式有反斜線的做 double escape ，然後 call nbconvert 的 api function (但它基本上是 call pandoc)做 notebook 和 markdown 之間的轉換。最後看 hexo 端是不是可以  call 這個 python app 去直接讀 notebook format 再轉成 markdown。

大致上的想法是這樣，但實作起來可能會有新的問題。不知道大家的看法如何？
